# config for testing

ckpt_path: "<path to the checkpoint folder>" # Model checkpoint path
save_dir: "<path to your data folder>" # Testing data path
output_path: "<path to your output folder>"/output_test.json" # Output data path
data_cls: "FormulaData"
key_map:
  concentration: "salt_molar_ratio"
  temperature: "temperature"

model:
  pretrain:
    model_config:
      graph_block:
        feature_layer:
          atom_embedding_dim: 16
          node_mlp_dims: [32, 32, 2]  # (hidden, out, layers)
          edge_mlp_dims: [32, 32, 2]  # (hidden, out, layers)
          act: gelu
        gnn_layer:
          gnn_type: EGT
          gnn_dims: [32, 32, 3]  # (hidden, out, layers)
          jk: cat
          act: gelu
          heads: 4
          at_channels: 8
          ffn_dims: [32, 2]  # (hidden, layers)
      readout_block:
        input_dim: 64
        hidden_dims: [256, 128, 16]
        output_dim: 1  

  model:
    aggr_block:
      node_emb_dim: 32
      node_att_dim: 32
      edge_emb_dim: 32
      edge_att_dim: 32
    readout_block:
      input_dim: 384
      hidden_dims: [512, 128, 16]
      output_dim: 1
    anion_block:
      input_dim: 400
      hidden_dims: [512, 128, 16]
      output_dim: 1
